# configuration
# fill in the course details
 
courseName: " Generative AI for Qauntum Computing and Machine Learning Software Implementations"

# small title that is at the top of every page
subtitle: "17-659 —  Generative AI for Qauntum Computing and Machine Learning Software Implementations — Summer Semester 2023"

# baseurl is the same as the name of the repository
baseurl: /2023-GenerativeAIForQuantum
# url where the required reading is available to download
docsUrl: "https://www.amazon.com/_/dp/1492039683?tag=oreilly20-20" 

# url where the student's grading info is kept
gradingUrl: "" 


# change only if you know what you are doing
collections:
  syllabus:
    output: true
defaults:
  - scope:
      path: ""
      type: syllabus
    values:
      layout: unit
